**Qn 3**

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np

In [ ]:
x1 = np.array([1, 2, 3])
x2 = 2*x1

y = np.array([4, 6, 8])

In [ ]:
all_ones = np.ones(x1.shape[0])
X = np.array([all_ones, x1, x2]).T

In [ ]:
X.shape

(3, 3)

In [ ]:
X

array([[1., 1., 2.],
       [1., 2., 4.],
       [1., 3., 6.]])

In [ ]:
def solve_normal_equation(X, y):
    try:
        theta = np.linalg.inv(X.T @ X) @ X.T @ y
        return theta
    except np.linalg.LinAlgError:
        print('The matrix is singular')
        print("X.T @ X = \n", X.T @ X)
        return None


In [ ]:
solve_normal_equation(X, y)

The matrix is singular
X.T @ X = 
 [[ 3.  6. 12.]
 [ 6. 14. 28.]
 [12. 28. 56.]]


In [ ]:
np.linalg.matrix_rank(X)

2

In [ ]:
np.linalg.matrix_rank(X.T @ X)

2

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

data = np.array([x1, x2]).T

lr.fit(data, y)
lr.coef_, lr.intercept_


(array([0.4, 0.8]), 2.0)

In [ ]:
# Regularization

eps = 1e-5
X = np.array([all_ones, x1, x2]).T
X = np.eye(3)*eps + X


In [ ]:
X

array([[1.00001, 1.     , 2.     ],
       [1.     , 2.00001, 4.     ],
       [1.     , 3.     , 6.00001]])

In [ ]:
np.linalg.matrix_rank(X)

3

In [ ]:
solve_normal_equation(X, y)

array([2.00023248, 1.19987743, 0.40001887])